export const surpriseMePrompts = [
  'A sunny day at the beach',
  'A cozy cabin in the woods',
  'A colorful hot air balloon in the sky',
  'A friendly dog playing fetch in the park',
  'A delicious slice of pizza',
  'A beautiful sunset over the mountains',
  'A field of blooming flowers',
  'A peaceful lake surrounded by trees',
  'A cute kitten playing with a ball of yarn',
  'A joyful family picnic in the park',
  'A classic red bicycle leaning against a fence',
  'A charming cafe with outdoor seating',
  'A smiling child blowing bubbles',
  'A tranquil waterfall in the forest',
  'A happy couple dancing in the rain',
  'A group of friends roasting marshmallows around a campfire',
  'A colorful rainbow after the rain',
  'A serene countryside landscape',
  'A whimsical carousel at a carnival',
  'A cozy fireplace on a winter evening',
  'A basket of freshly picked apples',
  'A scenic hiking trail through the mountains',
  'A graceful swan gliding on a pond',
  'A cheerful farmer\'s market with fresh produce',
  'A peaceful garden with blooming roses',
  'A festive holiday parade with marching bands',
  'A joyful birthday celebration with cake and balloons',
  'A vibrant street art mural',
  'A playful puppy chasing butterflies',
  'A majestic lighthouse overlooking the ocean',
  'A family of ducks swimming in a pond',
  'A cozy reading nook with a soft blanket',
  'A vintage bicycle with a basket of flowers',
  'A magical fairy tale castle in the clouds',
  'A picnic blanket spread out on green grass',
  'A colorful kite flying high in the sky',
  'A group of children playing tag in the park',
  'A peaceful meadow filled with wildflowers',
  'A family of deer grazing in a field',
  'A rustic wooden bridge over a bubbling stream',
  'A jar of fireflies lighting up the night',
  'A shiny red apple hanging from a tree',
  'A friendly scarecrow in a pumpkin patch',
  'A cluster of balloons floating in the sky',
  'A cozy log cabin nestled among pine trees',
  'A stack of pancakes with syrup and berries',
  'A sunny day at the park with a picnic blanket',
  'A colorful bouquet of flowers in a vase',
  'A row of colorful beach umbrellas on the sand',
  'A peaceful pond with lily pads and frogs',
  'A group of children playing hopscotch on the sidewalk',
  'A sparkling waterfall cascading down rocks',
];
